// Code generated by asyncapi-codegen-tools from asyncapi.yaml; DO NOT EDIT.

package apimatchmaking

const (
	EventTypeMatchMade = "match_made"
)

// MatchMadeEvent は ペアが成立した業務事実を表す matchmaking 発行イベント。
// subscriber: gateway (MatchID で in-memory dedup 後 WS 配信)。
// delivery は exactly-once 想定 (失敗時は元 JoinedAt で re-enqueue)。
type MatchMadeEvent struct {
	EventType string          `json:"event_type"`
	MatchID   string          `json:"match_id"`
	Players   []MatchedPlayer `json:"players"`
}

// MatchedPlayer
type MatchedPlayer struct {
	PlayerID string `json:"player_id"`
	DeckID   int64  `json:"deck_id"`
}
