// Code generated by scripts/generate_types.py; DO NOT EDIT.

package apimatchmaking

// One player entry inside a MatchMadeEvent.
type MatchedPlayer struct {
	// Player UUID.
	PlayerID string `json:"playerId"`
	// Deck id the player queued with.
	DeckID int64 `json:"deckId"`
}

// Pub/Sub message published to topic `matchmaking-events` when a
// pair of players is matched. Gateway subscriber は MatchID で
// インメモリ dedup する。
type MatchMadeEvent struct {
	// Event type discriminator, always "match_made".
	Type string `json:"type"`
	// ULID-based match id, prefixed `mch_`. Dedup key on the gateway side.
	MatchID string `json:"matchId"`
	// Two-element slice — order reflects queue pop order.
	Players []MatchedPlayer `json:"players"`
}
