// Package apimatchmaking provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apimatchmaking

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const (
	InternalAuthScopes internalAuthContextKey = "InternalAuth.Scopes"
)

// Defines values for MatchAbandonedRequestReason.
const (
	MatchAbandonedRequestReasonPlayerNotConnected MatchAbandonedRequestReason = "player_not_connected"
)

// Valid indicates whether the value is a known member of the MatchAbandonedRequestReason enum.
func (e MatchAbandonedRequestReason) Valid() bool {
	switch e {
	case MatchAbandonedRequestReasonPlayerNotConnected:
		return true
	default:
		return false
	}
}

// EnqueueRequest defines model for EnqueueRequest.
type EnqueueRequest struct {
	// DeckID Deck id the player queued with.
	DeckID int64 `json:"deck_id"`

	// GatewayInstanceID gateway プロセスが起動時に生成する識別子。matchmaking は最後に受け取った値を保持し、
	// 異なる値を受け取るとキューを空にしてから登録する。
	GatewayInstanceID string `json:"gateway_instance_id"`

	// Level Player level snapshot at enqueue time. 同上、enqueue 時点の固定値。
	Level int64 `json:"level"`

	// Name Player display name snapshot at enqueue time. matchmaking は account を呼ばず、
	// 呼び出し側 (gateway 経由) が /me で取得した値をそのまま受け取り queue entry と
	// match_made event に同梱する。
	Name string `json:"name"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Circuit closed / open
	Circuit string `json:"circuit"`

	// Status ok / degraded
	Status string `json:"status"`
}

// MatchAbandonedRequest defines model for MatchAbandonedRequest.
type MatchAbandonedRequest struct {
	// MatchID 破棄する成立済みマッチの識別子。
	MatchID string `json:"match_id"`

	// PlayerIDs 破棄するペアのプレイヤー識別子。
	PlayerIDs []string `json:"player_ids"`

	// Reason 不成立になった理由。理由ごとの件数をログから数えられるよう列挙で固定する。
	// player_not_connected は成立イベントの配信先が接続していなかった場合を表す。
	Reason MatchAbandonedRequestReason `json:"reason"`
}

// MatchAbandonedRequestReason 不成立になった理由。理由ごとの件数をログから数えられるよう列挙で固定する。
// player_not_connected は成立イベントの配信先が接続していなかった場合を表す。
type MatchAbandonedRequestReason string

// QueueSizeResponse defines model for QueueSizeResponse.
type QueueSizeResponse struct {
	// Size Current ZCARD of matchmaking:queue.
	Size int64 `json:"size"`
}

// internalAuthContextKey is the context key for InternalAuth security scheme
type internalAuthContextKey string

// EnqueuePlayerJSONRequestBody defines body for EnqueuePlayer for application/json ContentType.
type EnqueuePlayerJSONRequestBody = EnqueueRequest

// ReportMatchAbandonedJSONRequestBody defines body for ReportMatchAbandoned for application/json ContentType.
type ReportMatchAbandonedJSONRequestBody = MatchAbandonedRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CancelPlayer request
	CancelPlayer(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// EnqueuePlayerWithBody request with any body
	EnqueuePlayerWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	EnqueuePlayer(ctx context.Context, body EnqueuePlayerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReportMatchAbandonedWithBody request with any body
	ReportMatchAbandonedWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ReportMatchAbandoned(ctx context.Context, body ReportMatchAbandonedJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetQueueSize request
	GetQueueSize(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CancelPlayer(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelPlayerRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EnqueuePlayerWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEnqueuePlayerRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EnqueuePlayer(ctx context.Context, body EnqueuePlayerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEnqueuePlayerRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReportMatchAbandonedWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReportMatchAbandonedRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReportMatchAbandoned(ctx context.Context, body ReportMatchAbandonedJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReportMatchAbandonedRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetQueueSize(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetQueueSizeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCancelPlayerRequest generates requests for CancelPlayer
func NewCancelPlayerRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/cancel")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewEnqueuePlayerRequest calls the generic EnqueuePlayer builder with application/json body
func NewEnqueuePlayerRequest(server string, body EnqueuePlayerJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewEnqueuePlayerRequestWithBody(server, "application/json", bodyReader)
}

// NewEnqueuePlayerRequestWithBody generates requests for EnqueuePlayer with any type of body
func NewEnqueuePlayerRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/enqueue")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewReportMatchAbandonedRequest calls the generic ReportMatchAbandoned builder with application/json body
func NewReportMatchAbandonedRequest(server string, body ReportMatchAbandonedJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReportMatchAbandonedRequestWithBody(server, "application/json", bodyReader)
}

// NewReportMatchAbandonedRequestWithBody generates requests for ReportMatchAbandoned with any type of body
func NewReportMatchAbandonedRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/match-abandoned")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetQueueSizeRequest generates requests for GetQueueSize
func NewGetQueueSizeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/queue-size")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CancelPlayerWithResponse request
	CancelPlayerWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CancelPlayerResponse, error)

	// EnqueuePlayerWithBodyWithResponse request with any body
	EnqueuePlayerWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EnqueuePlayerResponse, error)

	EnqueuePlayerWithResponse(ctx context.Context, body EnqueuePlayerJSONRequestBody, reqEditors ...RequestEditorFn) (*EnqueuePlayerResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// ReportMatchAbandonedWithBodyWithResponse request with any body
	ReportMatchAbandonedWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReportMatchAbandonedResponse, error)

	ReportMatchAbandonedWithResponse(ctx context.Context, body ReportMatchAbandonedJSONRequestBody, reqEditors ...RequestEditorFn) (*ReportMatchAbandonedResponse, error)

	// GetQueueSizeWithResponse request
	GetQueueSizeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetQueueSizeResponse, error)
}

type CancelPlayerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r CancelPlayerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelPlayerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CancelPlayerResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type EnqueuePlayerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r EnqueuePlayerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r EnqueuePlayerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r EnqueuePlayerResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
	JSON503      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReportMatchAbandonedResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r ReportMatchAbandonedResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReportMatchAbandonedResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReportMatchAbandonedResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetQueueSizeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *QueueSizeResponse
}

// Status returns HTTPResponse.Status
func (r GetQueueSizeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetQueueSizeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetQueueSizeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CancelPlayerWithResponse request returning *CancelPlayerResponse
func (c *ClientWithResponses) CancelPlayerWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CancelPlayerResponse, error) {
	rsp, err := c.CancelPlayer(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelPlayerResponse(rsp)
}

// EnqueuePlayerWithBodyWithResponse request with arbitrary body returning *EnqueuePlayerResponse
func (c *ClientWithResponses) EnqueuePlayerWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EnqueuePlayerResponse, error) {
	rsp, err := c.EnqueuePlayerWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEnqueuePlayerResponse(rsp)
}

func (c *ClientWithResponses) EnqueuePlayerWithResponse(ctx context.Context, body EnqueuePlayerJSONRequestBody, reqEditors ...RequestEditorFn) (*EnqueuePlayerResponse, error) {
	rsp, err := c.EnqueuePlayer(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEnqueuePlayerResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ReportMatchAbandonedWithBodyWithResponse request with arbitrary body returning *ReportMatchAbandonedResponse
func (c *ClientWithResponses) ReportMatchAbandonedWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReportMatchAbandonedResponse, error) {
	rsp, err := c.ReportMatchAbandonedWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReportMatchAbandonedResponse(rsp)
}

func (c *ClientWithResponses) ReportMatchAbandonedWithResponse(ctx context.Context, body ReportMatchAbandonedJSONRequestBody, reqEditors ...RequestEditorFn) (*ReportMatchAbandonedResponse, error) {
	rsp, err := c.ReportMatchAbandoned(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReportMatchAbandonedResponse(rsp)
}

// GetQueueSizeWithResponse request returning *GetQueueSizeResponse
func (c *ClientWithResponses) GetQueueSizeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetQueueSizeResponse, error) {
	rsp, err := c.GetQueueSize(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetQueueSizeResponse(rsp)
}

// ParseCancelPlayerResponse parses an HTTP response from a CancelPlayerWithResponse call
func ParseCancelPlayerResponse(rsp *http.Response) (*CancelPlayerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelPlayerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseEnqueuePlayerResponse parses an HTTP response from a EnqueuePlayerWithResponse call
func ParseEnqueuePlayerResponse(rsp *http.Response) (*EnqueuePlayerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &EnqueuePlayerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseReportMatchAbandonedResponse parses an HTTP response from a ReportMatchAbandonedWithResponse call
func ParseReportMatchAbandonedResponse(rsp *http.Response) (*ReportMatchAbandonedResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReportMatchAbandonedResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetQueueSizeResponse parses an HTTP response from a GetQueueSizeWithResponse call
func ParseGetQueueSizeResponse(rsp *http.Response) (*GetQueueSizeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetQueueSizeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest QueueSizeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
