// Package apimatchmaking provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apimatchmaking

const (
	InternalAuthScopes internalAuthContextKey = "InternalAuth.Scopes"
)

// EnqueueRequest defines model for EnqueueRequest.
type EnqueueRequest struct {
	// DeckID Deck id the player queued with.
	DeckID int64 `json:"deck_id"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Circuit closed / open
	Circuit string `json:"circuit"`

	// Status ok / degraded
	Status string `json:"status"`
}

// QueueSizeResponse defines model for QueueSizeResponse.
type QueueSizeResponse struct {
	// Size Current ZCARD of matchmaking:queue.
	Size int64 `json:"size"`
}

// internalAuthContextKey is the context key for InternalAuth security scheme
type internalAuthContextKey string

// EnqueuePlayerJSONRequestBody defines body for EnqueuePlayer for application/json ContentType.
type EnqueuePlayerJSONRequestBody = EnqueueRequest
