// Code generated by scripts/generate_types.py; DO NOT EDIT.

package apimatchmaking

import "time"

// In-memory view of one player in the Upstash Redis Sorted Set.
// Exposed for gateway integration tests — production writes stay
// inside the matchmaking service's internal queue package.
type QueueEntry struct {
	// Player UUID.
	PlayerID string `json:"playerId"`
	// Deck id the player queued with.
	DeckID int64 `json:"deckId"`
	// ZADD timestamp.
	JoinedAt time.Time `json:"joinedAt"`
}
