// Code generated by scripts/generate_types.py; DO NOT EDIT.

package apimatchmaking

// Body of POST /internal/v1/enqueue. Gateway forwards the WS
// `matchmaking_start` message to this endpoint.
type EnqueueRequest struct {
	// Player UUID (plain UUID v4 string).
	PlayerID string `json:"playerId" binding:"required"`
	// Deck id the player queued with.
	DeckID int64 `json:"deckId" binding:"required"`
}

// Body of POST /internal/v1/cancel. Idempotent — 200 on success,
// 404 if the player was not in the queue.
type CancelRequest struct {
	// Player UUID to dequeue.
	PlayerID string `json:"playerId" binding:"required"`
}

// Body of GET /internal/v1/queue-size.
type QueueSizeResponse struct {
	// Current ZCARD of matchmaking:queue.
	Size int64 `json:"size"`
}
