#!/usr/bin/env python3
"""data/models.yaml から packages/api-matchmaking/*_gen.go を生成する。"""

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
MODELS_YAML = DATA_DIR / "models.yaml"

_GENERATED_HEADER = "// Code generated by scripts/generate_types.py; DO NOT EDIT."

def _format_go_tag(json_tag: str, extra: str | None) -> str:
    parts = [f'json:"{json_tag}"']
    if extra:
        parts.append(extra)
    return "`" + " ".join(parts) + "`"


def _needs_time_import(types: list[dict]) -> bool:
    for td in types:
        for field in td.get("fields", []):
            if "time.Time" in str(field.get("type", "")):
                return True
    return False


def _emit_go_file(path: Path, package: str, types: list[dict]) -> None:
    lines = [_GENERATED_HEADER, "", f"package {package}", ""]
    if _needs_time_import(types):
        lines += ["import \"time\"", ""]

    for td in types:
        name = td["name"]
        doc = td.get("doc")
        if doc:
            for line in doc.strip().splitlines():
                lines.append(f"// {line}" if line else "//")
        lines.append(f"type {name} struct {{")
        for field in td.get("fields", []):
            fname = field["name"]
            ftype = field["type"]
            fdoc = field.get("doc")
            if fdoc:
                for line in fdoc.strip().splitlines():
                    lines.append(f"\t// {line}" if line else "\t//")
            tag = _format_go_tag(field["json"], field.get("tag"))
            lines.append(f"\t{fname} {ftype} {tag}")
        lines.append("}")
        lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines).rstrip() + "\n")


def main() -> None:
    with open(MODELS_YAML, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    for file_def in data.get("files", []):
        rel_path = file_def["path"]
        package = file_def["package"]
        types = file_def["types"]
        out = ROOT / rel_path
        _emit_go_file(out, package, types)
        print(f"Generated → {rel_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
